from enum import Enum


class ErrorCode(Enum):
    '''
        THIS PART CONTAINS GENERAL ERROR CODES
    '''
    OBJECT_NOT_FOUND = 10001
    NOT_UPDATED = 10002
    NOT_INSERTED = 10009
    NOT_DELETED = 10003
    UNEXPECTED_DATA = 10009
    '''
        THIS PART CONTAINS ERROR CODE FOR AUTH SERVICE
    '''
    INCORRECT_USERNAME_OR_PASSWORD = 10004
    USER_NOT_FOUND = 10005
    WALLET_ADDRESS_IS_NOT_VALID = 10006
    TOO_SOON_TO_RESET = 10007
    RESET_REQUEST_NOT_FOUND = 1008
    '''
        THIS PART CONTAINS ERROR CODE FOR NOTIFICATION SERVICE
    '''
    MISSING_USER_PREF_FOR_NOTIFICATION = 10007
    EMAIL_SERVICE_DOWN = 10008
    '''
        THIS PART CONTAINS ERROR CODE FOR OTP
    '''
    WRONG_OTP_CODE = 10010
    EMAIL_SENT_ERROR = 10011
    INVALID_OTP_OR_EXPIRED = 10012
    '''
        THIS PART CONTAINS ERROR CODE FOR CONTENT ADDITION
    '''
    CONTENT_ID_IS_ALREADY_EXISTS = 10013
    '''
        THIS PART CONTAINS ERROR CODE FOR BRIDGE CREATION
    '''
    TARGET_ADDRESS_TYPE_WRONG = 10014
